services:
  lamoda-app:
    build:
      context: ./back
      dockerfile: Dockerfile
    container_name: lamoda_seller_app
    restart: always
    depends_on:
      lamoda-migrate:
        condition: service_completed_successfully
    env_file:
      - ./back/.env
    environment:
      - DB_HOST=lamoda-db
      - DB_PORT=5432
    ports:
      - "${SERVER_PORT:-8080}:${SERVER_PORT:-8080}"
    networks:
      - lamoda_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: kanban_frontend
    restart: always
    depends_on:
      - lamoda-app
    ports:
      - "3080:80"
    networks:
      - lamoda_network

  lamoda-db:
    image: postgres:15
    container_name: lamoda_seller_db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - lamoda_db_data:/var/lib/postgresql/data
    ports:
      - "5431:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - lamoda_network

  lamoda-migrate:
    image: migrate/migrate:v4.16.2
    depends_on:
      lamoda-db:
        condition: service_healthy
    env_file:
      - .env
    volumes:
      - ./back/migrations:/migrations
    command:
      - "-path=/migrations"
      - "-database=postgres://${DB_USER}:${DB_PASSWORD}@lamoda-db:5432/${DB_NAME}?sslmode=disable"
      - "up"
    restart: "no"
    networks:
      - lamoda_network

volumes:
  lamoda_db_data:

networks:
  lamoda_network:
    driver: bridge
